[package]
name = "sunset-db"
version = "0.0.1"
edition = "2021"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.3.2"

[dev-dependencies]
tempfile = "3.6.0"
